### ISSUE TITLE
Remove the notch when music is not playing

### ISSUE THREAD

**Issue by Shashwat-pd** [TheBoredTeam/boring.notch#100]
<img width="1800" alt="image" src="https://github.com/user-attachments/assets/a95cecf3-1358-41a9-bd5c-3b2c114c8540">
 
To enhance the user experience, it would be more effective to remove the notch when music is not playing and the user is engaging with other content. This approach ensures reduced distractions.

**Comment by Shashwat-pd** [comment]
I just figured out the problem is actually when two media is active. i.e I switched to Firefox by pausing the music from my keyboard. The app mistook the youtube video playing as the song.

**Comment by richardkunkli** [comment]
Hi,
Thanks for the feedback. Not an easy one to implement, but we are working on it. Currently it's in beta. Soon will be available in the upcoming release and users can test it. MacOS does not differentiate fullscreen media from fullscreen app, so a bit complicated to detect which one is happening.

**Comment by richardkunkli** [comment]
We have released a new version that has automatic fullscreen detection in beta. Hopefully it will resolve this issue. Note that this feature is still beta so might be unexpected behavior or false cases.
