### ISSUE TITLE
Music name is not updated for music playing in browser

### ISSUE THREAD

**Issue by kashishshah881** [TheBoredTeam/boring.notch#101]
Hello there,
Firstly great product. Really love it! 
The issue here is when I am playing music on firefox on youtube music. The first song will get updated on notch provided no other music was playing. 
But any change on the website doesnt get updated on the notch.

**Comment by richardkunkli** [comment]
Hi,
Thanks for the feedback. We are preparing to release a new update that includes a completely new backlogic, layout and experience. Hope that will solve this issue as well. Keep your eyes on the updates and join our Discord server if you'd us to keep you updated.
