### ISSUE TITLE
Option Request: Remove "Boring Notch" text from Boring Notch

### ISSUE THREAD

**Issue by MrUltimate** [TheBoredTeam/boring.notch#103]
Hi all,

First off, thank you for all your work on this. Already loving the app.

I wanted to request a small option—which would be the remove the "Boring Notch" text from the notch. I understand why this may have been added but for people who like clean designs, like myself, I find the text very distracting and it technically serves no purpose. 

It would also be interesting if that space could instead be repurposed for other controls and useful information like timezone clocks, weather, timers, etc.

Thanks!

**Comment by richardkunkli** [comment]
Hi,
Thanks for the feedback. New release incoming, so keep your eyes on the updates. In that release you will have the option to change that to a tab switcher.

**Comment by MrUltimate** [comment]
Oh amazing! Looks like the next release will be insane! Looking forward to it!

**Comment by nicholascarey** [comment]
+1
