### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Imwoan** [TheBoredTeam/boring.notch#105]
When i try to open this i just gives errors, please help. My discord if Imwoan if help through github isnt possible. sorry im new 
<img width="694" alt="Screenshot 2024-09-14 at 03 11 52" src="https://github.com/user-attachments/assets/64a7121a-b291-4f3b-a10e-8e8f389d99f7">
<img width="1392" alt="Screenshot 2024-09-14 at 03 15 45" src="https://github.com/user-attachments/assets/295432ad-807a-4595-a7f1-92ec998fe3ca">

**Comment by richardkunkli** [comment]
Hey,
Turn off auto manage code signing option and select Mac Developer cert instead. If you would like to just use the app, then I recommend you to join our Discord server and download the prerelease.
