### ISSUE TITLE
Feature Request: Option to hide / show media title on the bottom of the notch when switching between media

### ISSUE THREAD

**Issue by fahlisaputra** [TheBoredTeam/boring.notch#106]
Hi,
First of all, thank you for creating this fantastic app! I've been using it on my Macbook, and it works great.

I have a small feature request. Would it be possible to add an option to customize the visibility of the media title at the bottom of the notch when switching between media? It would be great to have the flexibility to hide or show this feature based on personal preference.

![FA4B5ACA-4728-46A5-9F06-3841BD762026_1_201_a](https://github.com/user-attachments/assets/f15c189c-0715-48dd-99b1-409deef32307)

I appreciate all the hard work that goes into building this app! Once again, thank you. Have a good day 🙌

**Comment by MannavaVivek** [comment]
I would like this feature. Right now the notch is displayed on full screen media content as well, and this pops up everytime I press any button. Kinda distracting. Would be great if we can hide the title

**Comment by richardkunkli** [comment]
Hi,
Thanks for the feedback. Could you be more specific? You can hide/unhide it in the settings.

**Comment by fahlisaputra** [comment]
Yeah, there’s a toggle in the settings to show or hide the media title😃

**Comment by MannavaVivek** [comment]
Wait there is an option for it already? Under which tab? 

<img width="603" alt="Screenshot 2024-09-18 at 10 06 09" src="https://github.com/user-attachments/assets/0725f42c-7dc2-4171-8218-93100270c2ea">

**Comment by richardkunkli** [comment]
It's obviously related to media, so media tab.😁

**Comment by richardkunkli** [comment]
Whaat, which version are you using? Could you attach me a screenshot showing the About tab, but before taking a photo click on the version number to reveal build number.

**Comment by richardkunkli** [comment]
Actually, no need for that. Come join us on Discord and I give you access to our prerelease.

**Comment by fahlisaputra** [comment]
![CleanShot 2024-09-18 at 16 27 17@2x](https://github.com/user-attachments/assets/74125dc2-8267-4945-a5ae-e2c6fbc8d54e)

I've tried building from the latest `panda-glows` source using Xcode, and the sneak peek setting is already there. Thanks @richardkunkli

**Comment by richardkunkli** [comment]
Nice. Note that the panda-glows branch does not include the HUDs.
