### ISSUE TITLE
Notch shapes does not match actual notch when started on external monitor

### ISSUE THREAD

**Issue by MannavaVivek** [TheBoredTeam/boring.notch#107]
Hi, first off, thanks for the amazing app. I just found a weird bug, wherein if I start boring.notch with an external monitor connected (Mine is an ultrawide curved display, it might differ when used with flat monitors) the notch comes up on the external monitor which is as expected. But, if I disconnect the external display, the notch does not match the actual notch on the MacBook Pro when it moves over. This does not happen if I start the notch on the MacBook first and then connect the external display. 
![boringnotch_mac](https://github.com/user-attachments/assets/be66c3e5-c23b-4383-b9c1-1e64c0b47778)

**Comment by richardkunkli** [comment]
Hi,
Thanks for the feedback. We are focused on macbooks with notch for now, so the external display handling won't be perfect. When you open the app it will check your main display and adapts for that. Won't change until a restart. We are preparing for a new release currently, and release after this one will focus on non-notch mac and external displays. 🔥

**Comment by brunorochadasilva** [comment]
+1 with the same bug (in my case it's two 27-inch 4k displays)
