### ISSUE TITLE
Does this also supports Mac(Book)s without a notch?

### ISSUE THREAD

**Issue by Ein-Tim** [TheBoredTeam/boring.notch#109]
I'm just wondering whether this will also work on my MacBook Air M1 without a notch? Some other apps with similar functionality do, so that's why I'm asking!

**Comment by richardkunkli** [comment]
Hi,
Absolutely, you can take a look at it, but we have been focused on notched macbooks. We are preparing for a new release for now, but the next release aimed to improve the experience of non-notch users and external displays.

**Comment by Ein-Tim** [comment]
Thanks!
