### ISSUE TITLE
support Apple Music

### ISSUE THREAD

**Issue by clausbertels** [TheBoredTeam/boring.notch#113]
I couldn't find any information on this, but it seems Apple Music is not supported? Spotify works fine. If Spotify is not running, it just shows the default I'm Handsome - Me track without album art.

I'm on Sequoia using 1.8

**Comment by richardkunkli** [comment]
Hi,
What version are you using? Of course the app supports Apple Music.

**Comment by clausbertels** [comment]
1.8

Turns out it took a restart of the computer.
