### ISSUE TITLE
Notch indicates media playing when it's not and vice versa

### ISSUE THREAD

**Issue by TrentMage** [TheBoredTeam/boring.notch#117]
The notch will occasionally indicate Spotify is playing music when the music is paused, and indicate it's not playing when it is. Additionally, the notch will show other media such as Youtube videos playing to be Spotify, even when the application is closed; however, the notch can still control the Youtube media.

**Comment by richardkunkli** [comment]
Hi,
Thanks for the feedback. We are using macOS global media center to detect playback, but so far that is very unreliable. Maybe we will give option to avoid using that and connect the app directly to a streaming service instead. Using their dedicated API.
