### ISSUE TITLE
Settings not saved

### ISSUE THREAD

**Issue by valentin56610** [TheBoredTeam/boring.notch#118]
Hello!

Just discovered your app and fell in love with it. Great, great job guys! 

One minor issue right now, it's that any setting I change while using the app, as soon as I close it and re open it, the changes I made are gone. For example, I am changing the minimum hover duration, setting it to 0, removing all of the menu bar icon and battery icons etc

Every time I re open the app I have to set this all up once again

Pretty sure that's not intended so I thought I'd let you know!

Cheers

**Comment by freepicheep** [comment]
I can't speak for the maintainers, but it's not a bug. The settings explicitly state that your settings will not be saved on restart until the project has matured. 
![CleanShot 2024-09-23 at 09 17 17](https://github.com/user-attachments/assets/1f2b89fa-a4d4-4a81-b02c-3349fa8c47c0)

**Comment by valentin56610** [comment]
Oh wow, ok! I will close this thread then! Thank you very much :)

**Comment by freepicheep** [comment]
Sounds good! Np. :)
