### ISSUE TITLE
Disable Notch UI in Fullscreen and on external displays

### ISSUE THREAD

**Issue by pandaboy6621** [TheBoredTeam/boring.notch#119]
I want the ability to hide the media icon and the sound icons in fullscreen and on external displays. But I still want the popup to appear when I mouse up.

**Comment by rahilthehill** [comment]
I agree!
For me personally the boring notch on a external display is jarring and usually covers content, if there is a quick option to "collapse it" when a external display is connected would be great, right now I sadly have to close and open the app every time I go on and off my external display.

**Comment by helplanes** [comment]
yes a button or a shortcut to quick collapse it would be great, would also solve the issue with it overlapping text from the menubar.

**Comment by richardkunkli** [comment]
Hi,
Please check #60 and #87 , it is a good practice to check the issues before posting one in case if it's already submitted.
