### ISSUE TITLE
notch size becomes too stretched when opened on external monitor

### ISSUE THREAD

**Issue by helplanes** [TheBoredTeam/boring.notch#125]
was better earlier, and normal in size.
![Screenshot 2024-10-11 at 8 11 56 PM](https://github.com/user-attachments/assets/1988ca74-2ecb-461d-9ddf-e2ae1253de33)

**Comment by richardkunkli** [comment]
Hi,
Thanks for the feedback. Please check #107

**Comment by richardkunkli** [comment]
Fixed it in the latest release (version 2.1).
