### ISSUE TITLE
Notch Area outlines menu bar.

### ISSUE THREAD

**Issue by BosKiToxX** [TheBoredTeam/boring.notch#128]
For intel macs without a notch the menu bar is smaller and the notch ocupies a bit of ussable screen. It would be nice if it would have a setting to change between sizes, or be able to resize it£
<img width="190" alt="Captura de pantalla 2024-10-12 a las 10 55 11" src="https://github.com/user-attachments/assets/f15a0c7e-9127-4bf7-bf72-a9c637e1b528">

**Comment by richardkunkli** [comment]
Hi,
Thanks for the feedback. We are releasing a new update soon, that works with non-notch macs better. Keep your eyes on the updates.

**Comment by richardkunkli** [comment]
Fixed it in the latest update.
