### ISSUE TITLE
Keeping the boring notch in place while moving between desktops

### ISSUE THREAD

**Issue by ozeno** [TheBoredTeam/boring.notch#133]
Currently when I move between desktops notch also moves with the desktop that I'm leaving and reappears on the desktop that I'm moving to. It's kind of a nitpick but it would be much better if the boring notch always stayed anchored to the actual notch as if it was also a physical thing rather than an app that moves between desktops.

Also thanks for the great work 👏

**Comment by richardkunkli** [comment]
Duplicate to #82
