### ISSUE TITLE
[FEATURE] Ability to resize notch when it's not collapsed

### ISSUE THREAD

**Issue by yigitalpsemerci** [TheBoredTeam/boring.notch#136]
**Is your feature request related to a problem? Please describe.**
Notch is overlapping with app bar on non Notch Mac.

**Describe the solution you'd like**
Would be nice if we can resize notch to fit menu bar.

**Additional context**
![image](https://github.com/user-attachments/assets/8e988308-8108-48ec-ab6c-10b429269663)

**Checks**
- [x] I haven't found any duplicates with my issue.

**Comment by iamharshdev** [comment]
Check the latest release we just released a new build for this.
