### ISSUE TITLE
[BUG] Calendar shows events 1 day early

### ISSUE THREAD

**Issue by nguyenjessev** [TheBoredTeam/boring.notch#139]
**Describe the bug**
Future calendar events seem to display 1 day early. For example, I'm seeing Sunday events displayed for today, Monday events displayed for Sunday, etc.

**To Reproduce**
1. Add an event to your calendar for tomorrow at some time.
2. Open the notch and view your events for today.
3. Tomorrow's event will show up for today.

**Expected behavior**
Events only display on their respective days.

**Screenshots or recordings**
<img width="257" alt="image" src="https://github.com/user-attachments/assets/6745cc8e-bde0-4f23-9180-5c64c8d08a25">

https://github.com/user-attachments/assets/b7a0c9d9-0626-40e7-9a68-b10ff67776bb

**Additional context**
Glowing Panda, macOS 15.1, MacBook Pro M1 Pro 16-inch

**Checks**
- [x] I haven't found any duplicates with my issue.

**Comment by richardkunkli** [comment]
Hi,
Thanks for the feedback. We are aware of this issue, caused by timezone differences. Working on it. Keep your eyes on updates.
