### ISSUE TITLE
What is the extensions tab?

### ISSUE THREAD

**Issue by Canoah** [TheBoredTeam/boring.notch#140]
in the config there is a tab called ¨extensions¨, but it seems that you cant do anything with it, is it something you are working on?

**Comment by richardkunkli** [comment]
Hi,

We have released our new feature, called extensions. This feature transforms the app to be easily extensible in the future. We are working on several extensions that we are going to release later. Also we opened up our platform so giving users and developers ability to make their own extensions and interact with BoringNotch. Keep your eyes on the updates.

**Comment by Canoah** [comment]
Thanks!, can’t wait to try them
