### ISSUE TITLE
[BUG] Calender is one day ahead 

### ISSUE THREAD

**Issue by v1nc3nth06** [TheBoredTeam/boring.notch#141]
The calendar is showing events for the day after

Here are some screenshots to show the bug 
<img width="319" alt="Screenshot 2024-10-19 at 11 42 27 PM" src="https://github.com/user-attachments/assets/2a969193-86ec-4828-8e6a-e9c4f867bd16">
<img width="273" alt="Screenshot 2024-10-19 at 11 40 19 PM" src="https://github.com/user-attachments/assets/6c199c18-bf00-4054-a14a-5a7bb3dbc38a">
As you can see the events are on a Monday but in the notch it shows on Sunday

**Comment by richardkunkli** [comment]
Hi,

We are aware of this bug, it caused by timezone differences, we need to implement timezone management in the logic. Thanks for the feedback by the way.

**Comment by richardkunkli** [comment]
Also the template for BUG reporting is on purpose, please do not remove the Checks sections, you reported a bug that already present in the issues.
