### ISSUE TITLE
[FEATURE] Completely hide black space on the top on non notch Mac

### ISSUE THREAD

**Issue by Romachamp** [TheBoredTeam/boring.notch#147]
**Is your feature request related to a problem? Please describe.**

If I’m on non notch Mac, there is a black thing on the top, which just takes space. 

**Describe the solution you'd like**

I would like to have an option to completely turn off black area, if nothing is going on. I mean, if there is music playing, sure, it can be displayed. Otherwise, just on hover the main black area, but the small one is not needed.

**Additional context**

Thank you, in advance!

**Checks**
- [x] I haven't found any duplicates with my issue.

**Comment by richardkunkli** [comment]
Duplicate to #137
