### ISSUE TITLE
[BUG] Settings opens when launching the app 

### ISSUE THREAD

**Issue by Mo-Almo** [TheBoredTeam/boring.notch#152]
Currently, there is no option to disable the pop-up setting window at launch, I wish this could be implemented in the future. 
- [x] I haven't found any duplicates with my issue.

**Comment by iamharshdev** [comment]
This is just for the first time and it's weird.

**Comment by Mo-Almo** [comment]
> This is just for the first time, and it's weird.

What do you mean just for the first time? I get the pop-up setting every time I open the app after quitting; I don't know if this is the intended behavior.

**Comment by richardkunkli** [comment]
The app activationPolicy is .accessory, that is causing some problems. Before we made this tweak (that causes settings window to open on start) the settings window opened in the background and had focus issues. This way that is resolved but opens on start. The current behavior will remain until we find a better solution.
