### ISSUE TITLE
[FEATURE] Allow use only on specific display (e.g., MBA but not Studio Display)

### ISSUE THREAD

**Issue by acousticbiker** [TheBoredTeam/boring.notch#156]
**Is your feature request related to a problem? Please describe.**
While I'm grateful for boringNotch for use on a MacBook Air with a notch, I would rather not see that (artificially created) notch in my menubar when using a Studio Display. 

**Describe the solution you'd like**
I imagine Settings > General > "Show on a specific display" is to select one display for boring.Notch to operate on when using more than one display at a time. Whether it be through this existing setting or a new one, it would be helpful to be able to select which displays boring.Notch operates on. I only ever use one display at a time and would ideally like for boring.Notch to operate when I'm using an MBA but not when using a Studio Display.

If this is not possible, an alternative could be to allow for the color of the notch to match the color of the menubar when using Studio Display.

**Checks**
- [x] I haven't found any duplicates with my issue.

**Comment by richardkunkli** [comment]
Hi,
We have this feature in the latest release, version 2.1. Check it out.🚀

**Comment by acousticbiker** [comment]
Thanks, Richard. I'm using v2.1 and don't see a way to only have it run on MBA while not running on Studio Display. Maybe I'm missing something?

If this functionality isn't possible, a variation on the alternative I mentioned above would be to have the notch only show up if the mouse hovers that area (similar to another request I see on allowing that for 'non-notched' Macs)

**Comment by richardkunkli** [comment]
Can you check for updates? Use the menubar icon / Check for updates button. If you need help join our Discord server.
