### ISSUE TITLE
[FEATURE] Show 'lost' menus

### ISSUE THREAD

**Issue by acousticbiker** [TheBoredTeam/boring.notch#157]
**Is your feature request related to a problem? Please describe.**
One of the flaws of the notch is losing menus for some apps when they extend into the area occupied by the notch.

**Describe the solution you'd like**
Is it possible for boring.Notch to show menus that are 'lost' due to the notch?

**Checks**
- [x] I haven't found any duplicates with my issue.

**Comment by richardkunkli** [comment]
Duplicate to #121
