### ISSUE TITLE
[BUG] - Animations become glitchy and more spastic when adding calendar.

### ISSUE THREAD

**Issue by sebibeau** [TheBoredTeam/boring.notch#166]
The boring.notch animations become more spastic and glitchy when adding more elements to the notch (like calendar).

When adding the calendar to the notch, opening the notch by hovering or clicking on it causes the animations to become jittery and not as smooth.

I understand that this newest version will have many bugs, and I know you guys are a small team. I felt it was best to let you know; this app has been great! Thanks!

**Comment by richardkunkli** [comment]
Hey,
Thanks for the feedback. We are going to release a new version tomorrow. Hopefully it will resolve this issue. Keep your eyes on the updates. 🚀

**Comment by freepicheep** [comment]
@sebibeau just checking to see if you noticed the same animation issues with the newest release.

**Comment by sebibeau** [comment]
Hey, thanks for asking!

Yeah, it seems much smoother now. Thanks for reaching out!
