### ISSUE TITLE
[FEATURE] Low power mode color

### ISSUE THREAD

**Issue by Illyze** [TheBoredTeam/boring.notch#173]
**Is your feature request related to a problem? Please describe.**
When in power mode the color is still white or green but not orange.
**Describe the solution you'd like**

**Additional context**

**Checks**
- [x] I haven't found any duplicates with my issue.

**Comment by freepicheep** [comment]
That's a great idea. I just made a working version and will open a PR when I polish it up. Hopefully it will be ready for the next release.
