### ISSUE TITLE
[BUG] Boring notch steals focus 

### ISSUE THREAD

**Issue by burgerga** [TheBoredTeam/boring.notch#175]
**Describe the bug**
Boring.notch steals focus and starts flickering

**To Reproduce**
This is probably the hard part, because I don't know how to force it.
What I currently do:
1. Play music in Youtube Music (installed as Chrome PWA)
2. Do stuff in iTerm 2 (typing, commands, etc.)
3. boring.notch steals focus (especially apparent if using the iTerm Hotkey window, since it will disappear), and starts flickering

**Expected behavior**
I can keep working

**Screenshots or recordings**

https://github.com/user-attachments/assets/4d62a120-3899-4256-94f7-e000209084f7

**Additional context**
Version 2.2 (but I think already present on 2.1, which was my first installed version)

**Checks**
- [x] I haven't found any duplicates with my issue.

**Comment by richardkunkli** [comment]
Hey,
Thanks for the feedback. We have identified the cause of the problem. Hopefully the next update will resolve it.
