### ISSUE TITLE
[BUG] Sneak Peek shortcut not working

### ISSUE THREAD

**Issue by bronisMateusz** [TheBoredTeam/boring.notch#176]
**Describe the bug**
Sneak Peak shortcut and record shortcut not working.

**To Reproduce**
1. Go to Settings
2. Click on Shortcuts
3. Try perform a shortcut
4. Try register a new shortcut
5. Perform shortcut didn't show sneak peek and register didn't register a new shortcut

**Expected behavior**
Show sneak peek and register new shortcut.

**Screenshots or recordings**
![Zrzut ekranu 2024-10-29 o 10 02 20](https://github.com/user-attachments/assets/a736f67a-49f5-4302-9674-0967b39b354b)

**Additional context**
- Boring Notch 2.2
- Mac OS 15.1 (24B83)
- MacBook Pro 14 2021

**Checks**
- [x] I haven't found any duplicates with my issue.

**Comment by freepicheep** [comment]
It's working for me on macOS 15.2 on a MacBook Pro 14 2021. I also tried it in a virtual machine with 15.1 and it worked fine. 
https://github.com/user-attachments/assets/9fdb7bfe-9238-4259-8376-f2f4b27bcd0b

Maybe use an app like [Pearcleaner](https://github.com/alienator88/Pearcleaner) to uninstall it then try again.

**Comment by bronisMateusz** [comment]
Ok, I have just checked more thoroughly. And it doesn't work only in combination with function keys, for example `command+F6`.

In addition, if you do manage to set up this shortcut, the sneak peak does not show up anyway. The notch gently dims for a moment, but nothing shows underneath it.

**Comment by freepicheep** [comment]
> Ok, I have just checked more thoroughly. And it doesn't work only in combination with function keys, for example `command+F6`.

Actually, I just checked and it does work with that shortcut if your function keys are set to be standard function keys instead of special features by default. If they are set to the special features (which it sounds like they are), you need to press `⌘ + fn + F6`. I'm still opening a PR to make the shortcut easier, but I wanted to clarify the issue.

**Comment by freepicheep** [comment]
Wonderful! You're very welcome. 

I don't think we can configure it to show the `fn` unfortunately...we rely on Sindre's [Keyboard Shortcuts](https://github.com/sindresorhus/KeyboardShortcuts) library for global shortcut functionality and I don't think it would be worth forking it and putting in the work to add that feature. Richard just merged my PR for setting the default hotkey to `⌘ + Shift + H`, so hopefully it won't be too confusing in the future.

@richardkunkli I think you should be able to close this issue now.
