### ISSUE TITLE
[BUG]Not able to add files to the shelf

### ISSUE THREAD

**Issue by deepexplorer06** [TheBoredTeam/boring.notch#178]
When we drag a file towards the notch, it is triggering the Mission Control instead of opening the shelf

Uploading Screen Recording 2024-10-30 at 2.10.36 AM.mov…

**Comment by pilisir** [comment]
Same problem here in 2.2, but everything ok in 2.1.

**Comment by richardkunkli** [comment]
Hey,
Thanks for letting us know. We have already addressed the cause of the issue. We are going to release a patch update to restore that functionality. Keep your eyes on the updates.
