### ISSUE TITLE
[FEATURE] Hide album art and spectrogram

### ISSUE THREAD

**Issue by Mesandro** [TheBoredTeam/boring.notch#179]
hello, congratulations for this wonderful app. I only use it for music control, but even though I disabled the "Enable music live activity" flag, it automatically reactivates after each play or pause. Is it possible to hide album art and spectrogram permanently? I'm not sure if it's a bug, but it would be even more minimal for me. I use Macbook Air M3 with Sequoia. Also my spectrogram always appears gray ;)

**Comment by richardkunkli** [comment]
Yes, indeed this is a bug. We have fixed it, we are going to release a patch update.

**Comment by richardkunkli** [comment]
Fixed in the new release, version 2.3. Please update the app.
