### ISSUE TITLE
[BUG] Text-scrolling on Song Names that are Short

### ISSUE THREAD

**Issue by MrTronMan** [TheBoredTeam/boring.notch#182]
**Describe the bug**
When changing the song while the notch is showing, if the text from the previous song causes text-scrolling, new songs that don't require text-scroll continue to scroll.

**To Reproduce**
1. Hover over Notch
2. Find a song with a long title
3. If any song after has as shorter title than required for text-scroll, it will still occur

**Expected behavior**
Text should not scroll on text that does not meet requirements for text-scroll.

**Screenshots or recordings**

https://github.com/user-attachments/assets/6c13518e-b7ac-4cc5-8e80-bfe175780f89

**Checks**
- [x] I haven't found any duplicates with my issue.

**Comment by richardkunkli** [comment]
Fixed it, will be released in the new update. Thanks for the feedback.

**Comment by MrTronMan** [comment]
Not a problem thank you!

**Comment by richardkunkli** [comment]
Fixed in the new release, version 2.3. Please update the app.
