### ISSUE TITLE
[BUG] Shelf not working

### ISSUE THREAD

**Issue by Dvssxlve** [TheBoredTeam/boring.notch#186]
My shelf isn´t working at all, just downloaded boring notch but for me this feature isn´t working. I´m not abled to drop files or use the AirDrop function

**Comment by richardkunkli** [comment]
Yes, indeed. We have fixed it. A new release is expected next week.

**Comment by richardkunkli** [comment]
Fixed in the new release, version 2.3. Please update the app.
