### ISSUE TITLE
HUD replacement function, brightness, sound

### ISSUE THREAD

**Issue by complexshaolong** [TheBoredTeam/boring.notch#192]
When will the HUD replacement function be launched?

**Comment by richardkunkli** [comment]
Hey,
Extensions are on the way, but we’re quite busy right now, so our usual progress can’t be maintained at the moment. Join our Discord server to stay tuned—I’m working on it and frequently share previews and development updates.

PS.: This space is dedicated for issues, if you have further questions feel free to ask them on our Discord server.
