### ISSUE TITLE
[BUG] The Install instructions mentions the incorrect github repository to clone

### ISSUE THREAD

**Issue by Alehaaaa** [TheBoredTeam/boring.notch#193]
**Checks**
- [x] I haven't found any duplicates with my issue.

The current git path mentioned for installation is:

```
git clone https://github.com/iamharshdev/boring.notch.git
cd boring.notch
```

When it should mention the current repository:
```
git clone https://github.com/TheBoredTeam/boring.notch.git
cd boring.notch
```

**Comment by Alexander5015** [comment]
Thanks, I just updated the readme with better git instructions
