### ISSUE TITLE
[BUG] Cannot disable 'Enable Music Live Activity'

### ISSUE THREAD

**Issue by VivekRadhakrishna77** [TheBoredTeam/boring.notch#203]
**Describe the bug**
When toggling the 'Enable Music Live Activity' to the off position, it works momentarily then auto re-enables itself. There's no way to keep the toggle in the off position.

**To Reproduce**

1. While playing media
2. Go to 'Settings' -> 'Media'
3. Toggle off ''Enable Music Live Activity'
4. Live media activity should disappear
5. Close the settings
6. Click anywhere on the screen
7. Live media activity re-appears

**Expected behavior**
When the toggle is set to off, Music Live activity should remain off until manually re-enabled.

**Screenshots or recordings**
https://github.com/user-attachments/assets/0aefedf7-f527-474c-9edb-9f82cb1cba1b

**Checks**
- [x] I haven't found any duplicates with my issue.

**Comment by richardkunkli** [comment]
Hey,
Yes, indeed this is bug. Fixed it already, update coming soon.

**Comment by richardkunkli** [comment]
Fixed in the new release, version 2.3. Please update the app.
