### ISSUE TITLE
[BUG] Time Doesn't Turn Over Into Hours

### ISSUE THREAD

**Issue by Vulpesq** [TheBoredTeam/boring.notch#204]
**Description:**
When a video or audio has a length past 60 minutes, It does not turn over into, for example, 1:05:00 but instead  65:00. I'm not sure if this is intended behavior or not, so I thought to report it.

**Steps to reproduce the behavior:**
1. Go to a video or audio longer than 60 minutes.
2. View the notch progress bar, the time will be broken in MMM:SS instead of HH:MM:SS.
3. Observe :O

**Expected behavior**
I imagine it's expected to turn over to HH:MM:SS. The length of the video below is 4:14:51 but the notch states 254:51 instead.

**Screenshots or recordings**
<img width="612" alt="Screenshot_2024-11-13_at_11 29 22_AM" src="https://github.com/user-attachments/assets/3a07729f-dfaa-44b7-a66d-8ae9829870e4">

**Additional context**
Add any other context about the problem here. Mentioning what version are you using.

**Checks**
-I haven't found any duplicates with my issue.

**Comment by Alexander5015** [comment]
This should be fixed in 2.3 which is being released now. @Vulpesq Let me know if you still have issues with this after the update
