### ISSUE TITLE
[FEATURE] Keyboard Status

### ISSUE THREAD

**Issue by boblukulus** [TheBoredTeam/boring.notch#237]
When you connect a external keyboard to your mac the keyboard lights (CapsLock; ScrollLock; NumLock) do not work.

I don't know if it is possible, but it would be a useful case for the notch to display if any of the keyboard feature is active.

**Comment by Kevlar35** [comment]
You can use Karabiner to synchronise your built-in keyboard leds.

https://github.com/pqrs-org/Karabiner-Elements

**Comment by Alexander5015** [comment]
I think a seperate application to address this like the one @Kevlar35 mentioned make more sense.
