### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kgeorge97** [TheBoredTeam/boring.notch#245]
Hi,

I just downloaded the app on MacBook today so I'm not sure if this is a bug. I tried watching the video on your site and it seems like there is a settings icon to add features and customize. However, when after downloading mine, it doesn't show any settings icon. I tried clicking on the application itself to see if that could open up a settings window, like some apps might have but the MacBook reacts as if nothing was selected. 

I've attached some screenshots of how it looks on my laptop.

![Xnip2024-12-16_22-14-54](https://github.com/user-attachments/assets/11a998b8-7ba5-472d-ab9c-c0f1a01d892b)
<img width="530" alt="image" src="https://github.com/user-attachments/assets/62fd47c4-fccb-461d-9edb-dd3b628ec758" />

**Comment by Alexander5015** [comment]
This is because the settings icon is disabled by default. There are two other ways of accessing settings. The first is to click on the menu bar icon and the second is to right click in the notch after opening it. Both of these will give you a menu with the option to open settings.
