### ISSUE TITLE
[FEATURE] Show only Spotify and not Videos being played 

### ISSUE THREAD

**Issue by kgeorge97** [TheBoredTeam/boring.notch#255]
**Is your feature request related to a problem? Please describe.**

So I'm not sure if this is something that's already in Settings but when a song plays, I like that I can play/pause from the notch but when videos play, I don't want that to appear on my notch because it's not important for me.

**Describe the solution you'd like**
Enable only audio files (i.e. songs from Spotify) to be on the notch and not audio from videos (i.e. from Youtube)

Apologies if I made any mistakes with this post as it's my first time using GitHub.

**Comment by Alexander5015** [comment]
This is great! Next time though please look to see if there are any duplicate posts like #146 although I know sometimes it can be hard if the keywords don't line up exactly.
