### ISSUE TITLE
[FEATURE] Drop shelf

### ISSUE THREAD

**Issue by Romachamp** [TheBoredTeam/boring.notch#30]
Hello, epic potato release's been pretty good and I'm pretty excited about new features(especially downloads). 

However, it would be also great, if the app had drop shelf feature. It is usually used for dragging and dropping files for some time, after which I can either do with them some actions like convert, share, airdrop or basically move to another place.

Please, consider adding this feature.

Thank you, in advance!

**Comment by richardkunkli** [comment]
Hi,
Thank you for the suggestion. We are focusing on the main functionality for now until every primary feature works as expected. Your suggested feature is on the roadmap. If you'd like to be informed about the upcoming features and dev updates, join our [Discord server](https://discord.gg/fRzYm3jtQY).

**Comment by richardkunkli** [comment]
TO-DO still, but if join are interested in helping us, join our [Discord](https://discord.gg/fRzYm3jtQY) then we can discuss the progress.

**Comment by N4tSu3** [comment]
> TO-DO still, but if join are interested in helping us, join our [Discord](https://discord.gg/fRzYm3jtQY) then we can discuss the progress.

Hello, I am really interested in the development of your Boring Notch and would like to be updated on the progress of it! But It turns out that all the links for the **Discord server** are invalid :/ 

Could it be that you didn't modify the discord invite link to have unlimited uses and not expire?

Anyways, hope to joint the server soon enough! And good luck on the progress of the new features coming up!

**Comment by richardkunkli** [comment]
Hi,
I have generated a new invite link. You can use [this](https://discord.gg/GvYcYpAKTu) link.

**Comment by N4tSu3** [comment]
> Hi, I have generated a new invite link. You can use [this](https://discord.gg/GvYcYpAKTu) link.

I am very sorry and this sounds a bit dumb but I wasn't able to see this message in time because of work. If you would be kind enough to invite me again, this would be awesome.

Here's my Discord user: _natsue 
(in case it is easier for you to invite me from the discord's Dm system)

**Comment by Romachamp** [comment]
https://discord.gg/WV5f4jGQ

**Comment by richardkunkli** [comment]
The discord button works just fine on our GitHub page, new users join us day by day. Try the link above.

**Comment by N4tSu3** [comment]
> The discord button works just fine on our GitHub page, new users join us day by day. Try the link above.

Oh, it works just fine, thank you! Sorry for bothering you.
