### ISSUE TITLE
Suggestion: Control the music volume

### ISSUE THREAD

**Issue by DinahWorld** [TheBoredTeam/boring.notch#32]
Add like a slider to control the music volume

PS : I love ur work !

**Comment by richardkunkli** [comment]
Thank you for the suggestion. We are already working on it, coming soon. 🚀
If you'd like to get the latest news about the upcoming features, join our [Discord server](https://discord.gg/fRzYm3jtQY).

**Comment by richardkunkli** [comment]
Volume control will be part of the HUD extension, keep your eyes on updates. Releasing it soon.
