### ISSUE TITLE
Menu Bar managers issues

### ISSUE THREAD

**Issue by rodolforfq** [TheBoredTeam/boring.notch#40]
Hello,

First of all. Awesome work! 😄 

Wanted to mention some issues that I can only reproduce when using a Menu Bar manager (I tried with both [Ice](https://github.com/jordanbaird/Ice) and [iBar](https://apps.apple.com/us/app/ibar-menubar-icon-control-tool/id6443843900?mt=12).

While I can still interact with the music controls when one these apps is running, clicking on the settings icon is next to impossible, specially with iBar. Ice also seems to interfere when using the "hidden bar" feature. I can also only toggle visibility when hovering near the lower section of the notch. Doing it from inside the bar itself (say, moving left or right towards the notch, from the menu bar), doesn't work as expected.

Glad to help with testing or anything else if needed. Thanks again for your great work 🏆

**Comment by richardkunkli** [comment]
Hi,
Thank you for the feedback. We will look into this issue. 🙌🏻

**Comment by rodolforfq** [comment]
Quick update:

This doesn't seem to be an issue with the latest Ice release (released today). At least not when I turn off the "Show on click" and "Show on hover" options since those appear to create a conflict with BoringNotch.

iBar doesn't play well with BoringNotch but with today's update, Ice has surpassed iBar features so I'm permanently switching to it. This issue can be closed from my point of view.

Thanks again!
