### ISSUE TITLE
Suggestion: Toggle to remove drop shadow

### ISSUE THREAD

**Issue by Samalander0** [TheBoredTeam/boring.notch#47]
I find the drop shadow to be a bit harsh - I feel like it makes the notch stand out a bit too much. This is a super simple feature, but if there was a toggle to disable the drop shadow, that would be amazing.

<img width="817" alt="Screenshot 2024-08-12 at 9 40 21 PM" src="https://github.com/user-attachments/assets/d0751402-03e0-4f5a-b38d-64f1157767aa">

**Comment by richardkunkli** [comment]
Hi,
Thank you for the feedback. The shadow has been disabled in [Romantic Lady (1.6)](https://github.com/iamharshdev/boring.notch/releases/tag/romantic-lady) release until we implement customization and better visuals.

**Comment by richardkunkli** [comment]
Shadow has been enabled but only if the notch is opened. The distraction is over. Also the shadow now works as expected, no clipping underneath the notch.
