### ISSUE TITLE
Physical Notch Cutting Off Texts

### ISSUE THREAD

**Issue by notjl** [TheBoredTeam/boring.notch#53]
Refer to the image below. The battery percentage and the media is cutoff, even the Boring Notch title is cut off.

I'm currently on an MBA M3 13" on the highest resolution
![image](https://github.com/user-attachments/assets/f723c2e6-e3f8-402d-b50b-6baa4db729c0)

**Comment by notjl** [comment]
I wanted to see what resolutions were affected by this bug.  My original post has a resolution of 2560x1664. These are the resolutions affected by this bug: 
`2560x1664` - doesn't show currently playing (song cover + wave), texts are cut, currently playing is not showing
`2048x1332` - song change is cut off, currently playing is not showing, settings icon is cut off
![image](https://github.com/user-attachments/assets/521a14cc-86c1-48ba-b19a-4a1387aa3115)
![image](https://github.com/user-attachments/assets/21d57dff-3ab6-4cf2-b806-ee62bd119184)

`1710x1112` - currently playing is cut off, song change is cut off
<img width="666" alt="image" src="https://github.com/user-attachments/assets/4546c240-05f7-4cba-bd31-1a08e7424dcc">
<img width="547" alt="image" src="https://github.com/user-attachments/assets/082455db-6de9-400a-8195-acaa31423b87">

The only guaranteed (so far from all the implemented features) compatible resolutions are: `1470x956` the default one and `1280x832`.

**Comment by richardkunkli** [comment]
Hi,
No worries, we have completely rewritten the layout and sizing so in the upcoming release this should not be a problem anymore. Keep your eyes on updates.
