### ISSUE TITLE
Remove battery status on Mac Studio

### ISSUE THREAD

**Issue by cal1b4n** [TheBoredTeam/boring.notch#56]
Currently, it displays 0% for the battery it doesn't even have. We should add a check for it to be disabled by default maybe

![Screenshot 2024-08-14 at 20 54 13](https://github.com/user-attachments/assets/a7008f4b-6eca-472d-af7a-bf1bbc0a33f8)

**Comment by ericfri** [comment]
Also, turn it off and reboot, it comes back.
