### ISSUE TITLE
Unable to install on macOS 13.6

### ISSUE THREAD

**Issue by Sualeheen** [TheBoredTeam/boring.notch#59]
Even though the MacOS I am running is 13.6 on my other laptop and your app requirements are macOS 12 ( If I am not wrong? ).
![WhatsApp Image 2024-08-15 at 11 53 56](https://github.com/user-attachments/assets/06a7a3b9-ac9a-41fc-bd6b-324d5be213d2)

**Comment by richardkunkli** [comment]
Hi,
The minimum macOS version is 14.2
