### ISSUE TITLE
Media playback active while in fullscreen

### ISSUE THREAD

**Issue by andremfp** [TheBoredTeam/boring.notch#60]
Hey guys, first of all, big kudos for the project!

I noticed that, while in fullscreen, the media playback animation remains active (see image below). I feel like it would be better not to show it while in full screen, or at least be able to disable it in the settings.

I'm on v1.8, on a MBP M3.

<img width="917" alt="image" src="https://github.com/user-attachments/assets/5006466c-47f5-4b94-9431-247e8c5e356e">

**Comment by richardkunkli** [comment]
Hi,
Thanks for the feedback. You're right, but we need further improvements to be able to achieve that. Keep your eyes on updates.

**Comment by michaeltikhonovsky** [comment]
I would also like to add to this and suggest adding the ability to select which apps it takes media info from. If I am watching a youtube video or something in my browser, I might not necessarily want the animation to play every time I stop/start the video or go to the next video.
