### ISSUE TITLE
Title bar of window stucks on full screen

### ISSUE THREAD

**Issue by themaharshpatel** [TheBoredTeam/boring.notch#61]
Steps:
- Full screen any window.
- hover to the boring notch
- title bar will stuck even after boring notch gets closed

View video for better understanding.

https://github.com/user-attachments/assets/0b61c3fd-b5bb-4be6-a9fe-bcc452b9db48

**Comment by richardkunkli** [comment]
Hi,
Thanks for the feedback. Indeed, this is a real bug, but this is related to macOS fullscreen behavior. It happens usually even using no apps for notch.

**Comment by shadmanZero** [comment]
in settings i guess if there is option to disable the notch it would be better for only full screen
