### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by MG353** [TheBoredTeam/boring.notch#65]
An idea that could be interesting to add: customization for the dimensions of the notch (open and closed), maybe show calendar events or reminders on the right side when notch is open. And the customization of the image when no media is playing.

Swiping over the notch to control media would be really cool.

But great app overall, amazing job!

**Comment by richardkunkli** [comment]
Hi,
Thanks for the feedback. It is on the roadmap, you can find in near the end of our readme.
