### ISSUE TITLE
Feature Suggestion: Camera Mirror View from NotchNook

### ISSUE THREAD

**Issue by programister42** [TheBoredTeam/boring.notch#71]
Hi! I really like the mirror feature in the [NotchNook](https://lo.cafe/notchnook) app. It's so useful for checking my frame before meetings and just to know if I look neat. I think it would be amazing if you could add a similar feature to this app because I really like using it and the way it's developing ❤️

**Comment by richardkunkli** [comment]
Hi,
Thanks for the feedback. It will be released in a couple of days.

**Comment by richardkunkli** [comment]
We have already fixed it, but do you think a gray color would be better? I checked it and actually I like it.

**Comment by programister42** [comment]
> We have already fixed it, but do you think a gray color would be better? I checked it and actually I like it.

I made it gray only because there was already gray text in the header, I mean "Boring Notch" title on the left

**Comment by iamharshdev** [comment]
@programister42 We have already built it.

![image](https://github.com/user-attachments/assets/77bc4ae2-cc3b-4244-b2ee-4ade8803bebe)
