### ISSUE TITLE
BoringNotch view slightly mismatches the actual notch shape

### ISSUE THREAD

**Issue by programister42** [TheBoredTeam/boring.notch#72]
~~You guys are probably gonna hate me for this~~, I hope you don't 🙏
As you may know, Apple does not actually use circles, but so-called squircles to design the rounded corners of its products. So a completely round clip path doesn't really fit the physical shape of the notch. I suggest two ways to deal with this:

1. In a closed state, we can make its width smaller than the actual notch and just expand it when needed, as it works right now.
2. We can try to replicate the actual squirlcle curved path of the physical notch, which can be more complicated to achieve.

> [Rounded Corners in the Apple Ecosystem](https://medium.com/minimal-notes/rounded-corners-in-the-apple-ecosystem-1b3f45e18fcc)

https://github.com/user-attachments/assets/80d7eb1c-d808-469d-a397-e7ca079847fd

https://github.com/user-attachments/assets/b2b3359b-64c1-443b-a7f8-4e891fc497c9

**Comment by richardkunkli** [comment]
Hi,
Thank you for the feedback. The window size is calculated by macOS built-in insets and sizes. Should be perfect on every device. Anyway, we'll take a look at this problem. Maybe we just have to fine-tune the corner radius a little.
