### ISSUE TITLE
Media Playback doesnt match media

### ISSUE THREAD

**Issue by johndfields** [TheBoredTeam/boring.notch#73]
The default "I'm Handsome" by "Me" 

I noticed it doesnt change to the media of the computer (I.E. doesnt show the youtube playing like the standard MacOS player does) 

<img width="357" alt="image" src="https://github.com/user-attachments/assets/b8176a21-20d9-4c9d-ad45-a5fa3a14c1ba">

<img width="560" alt="image" src="https://github.com/user-attachments/assets/2079c797-75be-4538-86a4-654f84d16067">

**Comment by richardkunkli** [comment]
Hi,
Thanks for the feedback. It should work as expected. Sometimes macOS does not provide the media, maybe try to pause and start the media. We'll take a look at it anyway,

**Comment by nickwright99** [comment]
I'm having the same issue.

Works fine with Spotify, always shows the right thing.

But then I switch to YouTube, or Instagram on my desktop and it just shows the previous Spotify song as playing. 

It clearly recognises some sort of media is playing, but seems to assume its still the Spotify song.

**Comment by richardkunkli** [comment]
Hopefully the new update resolved this issue. Reopen it if still persist.
