### ISSUE TITLE
Please can we set the display to use BoringNotch on?

### ISSUE THREAD

**Issue by jamesjingyi** [TheBoredTeam/boring.notch#74]
Hi I use multiple external monitors and would like BoringNotch to only be active on my MacBook's display, but it's not the display that I choose as my 'main' (i.e. the one in Displays > Arrange that you have the menu bar set to).

I don't have it as the main display just because some applications like to put prompts etc on that display and I would miss them, but I would like to have BoringNotch only work on my MacBook's display, i.e. the one with a notch.

Thanks!

**Comment by mcvons** [comment]
similarly - boring notch (jan 2025) has been showing up on external display - which is set as main display - but now it's only on the laptop - restarting doesn't reset. Tried reinstalling - that worked for a moment - and then it went back down to the laptop. must be missing something? thank you
