### ISSUE TITLE
Features suggestions from notchNook

### ISSUE THREAD

**Issue by cedricloneux** [TheBoredTeam/boring.notch#75]
Here are good and inspiring features I found in a similar paid app:
- mirror (camera access)
- tray & airdrop (Able to drag and drop files inside the notch, either in a tray or for airdrop)

(See notchNook)

**Comment by richardkunkli** [comment]
Hi,
We have a prerelease which includes mirror. Shelf (tray with AirDrop) is under development. If you want to give it a try, join our [Discord server](https://discord.gg/GvYcYpAKTu).

**Comment by iamharshdev** [comment]
@cedricloneux Mirror is set to be out by the next release.

![image](https://github.com/user-attachments/assets/ed465449-7503-4761-9ac5-5a1cf6ea8cae)

**Comment by DinahWorld** [comment]
Ommg so pretty
