### ISSUE TITLE
Settings Reset After App Restart

### ISSUE THREAD

**Issue by ACh-K** [TheBoredTeam/boring.notch#79]
After restarting the app, some user settings are reset to default. This occurs every time the app is reopened.

https://github.com/user-attachments/assets/a434f85e-c137-4d63-9d42-09b63a7140c1

There's also another problem that the settings window opens every time the app is launched.

**Comment by RyloRiz** [comment]
Is there a future date or release we can look forward to when this functionality will be restored?
