### ISSUE TITLE
App Installation Support

### ISSUE THREAD

**Issue by Arch2320** [TheBoredTeam/boring.notch#81]
Hi, 

Loving the design for your app and super keen to try it out. I am trying to install it onto my mac using your instructions and when I hit Cmd + R it gives me an error. I am new to Xcode so could be doing it wrong. Would be super useful if there was an installation demo video of some sort.

Thanks!
![Screenshot 2024-08-29 at 12 36 58 AM](https://github.com/user-attachments/assets/94ee42b9-319e-4e28-a108-cf96b63f542e)

**Comment by mustafakendiguzel** [comment]
Are you gonna developing the boring notch or you just want to use for personal case ? @Arch2320

**Comment by Arch2320** [comment]
For personal use

**Comment by mustafakendiguzel** [comment]
> For personal use

For personal use you not need to install on Xcode you can install the [dmg file ](https://github.com/iamharshdev/boring.notch/releases)

**Comment by erichobson** [comment]
<img width="927" alt="Screenshot 2024-09-10 at 9 21 38 PM" src="https://github.com/user-attachments/assets/9dbb07d9-9ca6-499d-9a55-d7c2e80f1912">

Follow these steps and you should then be able to run using `Cmd + R`. The team should be you and the signing certificate *should* be set to `Development`. This is what worked for me, so I hope it does for you!
