### ISSUE TITLE
Transition opacity for album picture.

### ISSUE THREAD

**Issue by igorkra** [TheBoredTeam/boring.notch#86]
When the popup with the album picture appears, there is a moment when the shape of the notch itself is visible.
It would be good to add a transparency animation for the picture, so that it would disappear before the popup disappears.
<img width="277" alt="Screenshot 2024-09-02 at 22 44 47" src="https://github.com/user-attachments/assets/b09d6a0f-c495-4caf-b341-5f8760797b07">

**Comment by richardkunkli** [comment]
Hi,
Thanks for the feedback. We are preparing to release a new version. In the new release we have completely rewritten the layout and behavior of the notch itself. I believe it will solve your problem as well.
