### ISSUE TITLE
Option to hide Music title/Youtube title when on play 

### ISSUE THREAD

**Issue by roychung96** [TheBoredTeam/boring.notch#87]
Option to hide pop up title like this
<img width="337" alt="image" src="https://github.com/user-attachments/assets/e7eb683b-2166-45d0-98fb-f5da9053d5f4">

**Comment by richardkunkli** [comment]
Hi,
Thanks for the feedback. We are preparing a new release and it will include a new feature as a beta that hides the live activity automatically on fullscreen media playback.
