### ISSUE TITLE
When playing music, the extra black space is not flush with the notch. It is slightly smaller.

### ISSUE THREAD

**Issue by SirFonzie-D** [TheBoredTeam/boring.notch#90]
What I noticed during playing music was like the title describes, the space it uses for the album cover and the music animation is slightly smaller than the notch, causing the notch to not be a completely straight line. I would suggest adding just a few more pixels, if this is a common issue. I use a MacBook Air M3 (13 inch). I hope its visible, since it is a very slight difference in size. 
![IMG_7698](https://github.com/user-attachments/assets/77bbfa72-7343-415a-b807-e7bc7afbbb59)

**Comment by richardkunkli** [comment]
Hi,
Thanks for the feedback. We are preparing to release a new version that includes a fully rewritten layout and sizing. I believe this problem has been resolved.
