### ISSUE TITLE
Notch visible during lock screen transition

### ISSUE THREAD

**Issue by aidan-yip** [TheBoredTeam/boring.notch#92]
Notch is visible when locking Macbook and looks a little strange. Since you can see where it clips at the top.

Device:
M3 MacBook Air 

![Screenshot 2024-09-05 at 3 09 07 PM](https://github.com/user-attachments/assets/9c499501-603e-4186-b02d-9cc83c6f72b3)

**Comment by richardkunkli** [comment]
Hi,
Thanks for the feedback. We are preparing to release a new update that includes a completely rewritten layout and behavior. Please let me know if the issue still persists in the new update.

**Comment by aidan-yip** [comment]
Absolutely, will do! I just wanted to say I really enjoy this app and it's functionality. Keep up the great work! I'm surprised Apple hasn't added this natively as an option at least.
