### ISSUE TITLE
Spectrogram inaccurate 

### ISSUE THREAD

**Issue by Stargorithm** [TheBoredTeam/boring.notch#93]
Ive noticed that the spectrogram is inaccurate, to confirm this I even played a song that had no sound and it still played the same animation.

**Comment by richardkunkli** [comment]
Hi,
Thanks for the feedback. Even though you are right, this is not a bug. We are building the app to be lightweight and continuous audio analyzation would be resource hungry. Later audio-synced spectrogram will be available, but disabled by default.

**Comment by Stargorithm** [comment]
Ohhhhh, I see! That makes sense! :)
