### ISSUE TITLE
Boring Notch not in focus

### ISSUE THREAD

**Issue by Stargorithm** [TheBoredTeam/boring.notch#94]
I have to click on the notch once before it puts it in focus, It would be nice if it put it in focus on hover!

**Comment by rodalpho** [comment]
Agree, would like clickthrough to be active.

**Comment by richardkunkli** [comment]
Hi,
Thanks for the feedback. It is designed to not be focused. We uses NSPanel for the window that has a styleMask settings called .nonActivatingPanel. A common practice for panels and HUDs. Could you please describe why it has to be focused? We can change that in case of need.

**Comment by richardkunkli** [comment]
It sounds strange, haven't experienced this at all. What version are you using? You can check the it in the About tab, clicking on the release version number reveals the build number as well.

**Comment by Stargorithm** [comment]
1.8 (Sleeping snail)

**Comment by richardkunkli** [comment]
We are preparing for a new release called **Glowing Panda**. The release includes a completely rewritten layout and behavior. Hope it solves this bug. If you are familiar with Xcode you can build it for yourself, find the code in the [`panda-glows`](https://github.com/TheBoredTeam/boring.notch/tree/panda-glows) branch.

**Comment by rodalpho** [comment]
Yes definitely happens in 1.8. This is a common MacOS interface gotcha called clickthrough, where you need to click to focus a window and *then* have to click again to actually do anything inside that window. The problem is Apple implements it inconsistently, you can click directly on a link in Safari etc, and similar I would like to immediately single click on the play/pause button after bringing up the notch media panel.

**Comment by Stargorithm** [comment]
Unfortunately i'm not too experienced with xcode yet. However, when the update releases ill make sure!

**Comment by richardkunkli** [comment]
These are not errors, but warnings. The app is fully functional with those. No worries.

**Comment by Stargorithm** [comment]
@richardkunkli I run the code and I get the "Build successful message but nothing happens?

**Comment by richardkunkli** [comment]
Join us on Discord and discuss the rest there. We'll guide you how to setup the project if you have no success with that.
