### ISSUE TITLE
Blur Album Cover when minimized

### ISSUE THREAD

**Issue by condense-fidelity-elope** [TheBoredTeam/boring.notch#95]
When the notch is in minimized, the album cover should be blurred. Because just the downscale cover is a pixelly mess and just looks super ugly and doesn't really fit into the whole apple aesthetic. Like maybe the blur decreased and increases in intensity as you expand and minimize the notch.
<img width="1470" alt="Screenshot 2024-09-09 at 9 38 27 PM" src="https://github.com/user-attachments/assets/3f187372-7070-47e0-ac0c-a185c8966c0f">
<img width="1470" alt="brah" src="https://github.com/user-attachments/assets/2d57b9a3-2304-45ab-b659-6d9002c9622a">

**Comment by condense-fidelity-elope** [comment]
That's rad but I think you misunderstood what I said. This is not a bug, but a feature request.

**Comment by richardkunkli** [comment]
Oh, sorry about that. The expected behavior is similar to what Apple does in the dynamic notch. I don't think blurring the album art would be a great choice.
